import styles from "../styles/Home.module.css";
import style from "../styles/Course_Details.module.css";
import design from "../styles/Services.module.css";
// import globalStyle from "../styles/Global.module.css";
// import Service_two from "../components/Service_two";
import Service_two from "../components/Service_two";
import Head from "next/head";
import Image from "next/image";
import { Raleway, Poppins } from "@next/font/google";
import { Container, Row, Col, Accordion } from "react-bootstrap";
import ContactUs from "../components/ContactUs";

// const Heading = Raleway({ weight: ["600", "700"], subsets: ["sans-serif"] });
// const paragraph_font = Poppins({ weight: "500", subsets: ["sans-serif"] });

const Services = () => {
  return (
    <>
      <Head>
        <title>Basic Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Raleway:wght@600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
          rel="stylesheet"
        />
        <script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
        ></script>
      </Head>

      <section className={`primary_background`}>
        <div className="container ">
          <div className={`card border-0 shadow  ${design.topCard}`}>
            <div className="text-center">
              <h1 className={design.topCardText}>
                Our <span className={styles.ds}>Digital Services</span> <br />
                Special For You
              </h1>
            </div>
          </div>
        </div>
      </section>
      <section>
        <Service_two />
      </section>
      <section>
        <ContactUs />
      </section>
    </>
  );
};

export default Services;