import styles from "../styles/Home.module.css";
import style from "../styles/Course_Details.module.css";
import design from "../styles/Services.module.css";
// import globalStyle from "../styles/Global.module.css";
// import Service_two from "../components/Service_two";
import Service_two from "../components/Service_two";
import Head from "next/head";
import Image from "next/image";
import { Raleway, Poppins } from "@next/font/google";
import { Container, Row, Col, Accordion } from "react-bootstrap";
import ContactUs from "../components/ContactUs";
import TopHeader from "../components/shared/TopHeader";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import Description from "../components/service/Description";
import MarketingSection from "../components/service/MarketingSection";
import BrandingSection from "../components/service/BrandingSection";
import SectionTitle from "../components/shared/SectionTitle";
import SearchPopUp from "../components/shared/SearchPopUp";
import TopScrolling from "../components/shared/ScrollToTop";

// const Heading = Raleway({ weight: ["600", "700"], subsets: ["sans-serif"] });
// const paragraph_font = Poppins({ weight: "500", subsets: ["sans-serif"] });

const Services = () => {
  return (
    <>
      <Head>
        <title>Upturn Idea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Raleway:wght@600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
          rel="stylesheet"
        />
        <script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
        ></script>
      </Head>

      <TopHeader pageName={"Services"} />
      {/* <section className={`primary_background`}>
        <div className="container ">
          <div className={`card border-0 shadow  ${design.topCard}`}>
            <div className="text-center">
              <h1 className={design.topCardText}>
                Our <span className={styles.ds}>Digital Services</span> <br />
                Special For You
              </h1>
            </div>
          </div>
        </div>
      </section> */}
      <section style={{ marginTop: "120px" }}>
        <div className="container mt-3 ">
          <div className="row gx-5">
            <div className="col-4 ">
              <a
                href="#marketingSection"
                style={{
                  backgroundColor: "#F5FAFF",
                  padding: "30px 20px",
                  paddingLeft: "35px",
                }}
                className="d-flex align-items-center justify-content-between serviceBtn"
              >
                <span className="fw-bold  fs-5  ">Marketing Strategy</span>
                <button className="servicesMiniBtn rounded-5 ms-4 ">
                  <ArrowForwardIcon className="servicesBtnIcon fw-bold  " />
                </button>
              </a>
              <a
                href="#brandingSection"
                style={{
                  backgroundColor: "#F5FAFF",
                  padding: "30px 20px",
                  paddingLeft: "35px",
                }}
                className="d-flex align-items-center justify-content-between serviceBtn mt-3 "
              >
                <span className="fw-bold  fs-5  ">Branding Strategy</span>
                <button className="servicesMiniBtn rounded-5 ms-4 ">
                  <ArrowForwardIcon className="servicesBtnIcon fw-bold  " />
                </button>
              </a>

              <div className="serviceCard bg-black text-center p-4 mt-5  ">
                <img
                  src="/images/service/phone-call.png"
                  alt="call"
                  height={70}
                  width={70}
                />

                <h4 className="fs-1 fw-bold mt-3 ls-2 text-white  ">
                  Looking for <br /> Top Digital <br /> service?
                </h4>
                <p className="text-uppercase mt-5 ls-2 text-white  pb-0 mb-0 ">
                  Call anytime
                </p>
                <p className="mt-2 ls-2 text-white  "> +8801921921921</p>
              </div>
            </div>
            <div className="col-8 ">
              <img
                src="/images/service/analisis.png"
                style={{ width: "100%", height: "auto" }}
                alt=""
              />
              <MarketingSection />

              <BrandingSection />
            </div>
          </div>
        </div>
      </section>
      <section className="" style={{ marginTop: "120px" }}>
        <Service_two />
      </section>
      <section className="" style={{ marginTop: "80px" }}>
        <SectionTitle text="Contact With Us" />
        <ContactUs />
      </section>
      <SearchPopUp />
      <TopScrolling />
    </>
  );
};

export default Services;
