import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import style from "../../styles/Course_Details.module.css";
import Head from "next/head";
import Image from "next/image";
import { Raleway, Poppins } from "@next/font/google";
import { Container, Row, Col, Accordion } from "react-bootstrap";
import Link from "next/link";

const slug = ({ myCourse }) => {
  const router = useRouter();
  // console.log(props);
  if (!myCourse) {
    return <div>Loading...</div>;
  }
  const [course, setCourses] = useState(myCourse);

  const [isFixed, setIsFixed] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      const section = document.getElementById('fixedDivId');
      if (section) {
        const sectionTop = section.offsetTop;
        const scrollPosition = window.scrollY;
        console.log("section top", sectionTop);
        console.log("scrollPosition", scrollPosition);

        // Check if the scroll position is greater than or equal to the section's top position
        // If it is, fix the section
        setIsFixed(scrollPosition >= sectionTop);
      }
    };

    // Add scroll event listener
    window.addEventListener('scroll', handleScroll);

    // Cleanup function
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);


  // console.log(course.course);
  return (
    <div>
      <Head>
        <title>Basic Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Raleway:wght@600&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
          rel="stylesheet"
        />
        <script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
        ></script>
      </Head>
      {course.course.map((course) => {
        return (
          <section key={course.slug} style={{ background: "#FEFAED" }}>
            <div className="container">
              <div className="row g-0 gx-5">
                <div className="col-12 col-lg-7" style={{ marginTop: "40px" }}>
                  <h1 key={course.slug} className={style.heroH1}>
                    {course.title}
                  </h1>
                  <p className={styles.p}>
                    Unlock Your Potential Comprehensive Course to Develop Your
                    Skills and Strategies to Reach Your Goals
                  </p>
                  <h3 className={style.heroH3}>Course Instructor</h3>
                  <div
                    className="card border-0 shadow"
                    style={{ marginTop: "30px" }}
                  >
                    <div className="row">
                      <div className="col-12 col-lg-3">
                        <div
                          className={`text-center text-lg-start ${style.imgCard1}`}
                        >
                          <Image
                            src="/home/mentorOnSlug.png"
                            alt=""
                            height="105"
                            width="105"
                            layout="fixed"
                          />
                        </div>
                      </div>

                      <div className="col-12 col-lg-9">
                        <div
                          className="text-center text-lg-start"
                          style={{ marginTop: "30px" }}
                        >
                          <h4 className={style.heroH4}>{course.mentorName}</h4>
                          <p
                            className={`text-center text-lg-start ${style.heroP2}`}
                          >
                            {/* Digital Content Creator <br /> */}
                            Author, Basic Education
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* ======== What you'll learn ======== */}

                  {/* <h3 className={style.heroH3}>What you'll learn</h3>
                  <div className={`card border-0 shadow ${style.learnCard}`}>
                    <div className="d-flex" style={{ marginTop: "40px" }}>
                      <div className={style.heroIcon}>
                        <Image
                          src="/home/Vector (8).png"
                          alt=""
                          height="16"
                          width="26"
                          fixed
                        />
                      </div>
                      <div>
                        <p
                          className={style.heroP2}
                          style={{ marginLeft: "22px" }}
                        >
                          You will have intermediate to expert level knowledge
                          of graphic design theory that you will immediately be
                          able to apply to your career, job, hobby, or company.
                        </p>
                      </div>
                    </div>

                    <div className="d-flex">
                      <div className={style.heroIcon}>
                        <Image
                          src="/home/Vector (8).png"
                          alt=""
                          height="16"
                          width="26"
                          fixed
                        />
                      </div>
                      <div>
                        <p
                          className={style.heroP2}
                          style={{ marginLeft: "22px" }}
                        >
                          You will be given a major overview of the most common
                          graphic design practices and the thought process
                          behind these principles.
                        </p>
                      </div>
                    </div>

                    <div className="d-flex">
                      <div className={style.heroIcon}>
                        <Image
                          src="/home/Vector (8).png"
                          alt=""
                          height="16"
                          width="26"
                          fixed
                        />
                      </div>
                      <div>
                        <p
                          className={style.heroP2}
                          style={{ marginLeft: "22px" }}
                        >
                          You will be given real-world, applicable projects that
                          you can follow along with and practice.
                        </p>
                      </div>
                    </div>

                    <div className="d-flex">
                      <div
                        className={style.heroIcon}
                        style={{ color: "#414141" }}
                      >
                        <Image
                          src="/home/Vector (8).png"
                          alt=""
                          height="16"
                          width="26"
                          layout="fixed"
                        />
                      </div>
                      <div>
                        <p style={{ marginLeft: "22px", color: "#414141" }}>
                          You will achieve the experience and knowledge to take
                          graphic design fundamentals and apply them in your
                          everyday life.
                        </p>
                      </div>
                    </div>

                    {/* <div className={`d-flex ${style.heroIcon}`}>
                      <h6 className={style.heroMore}>Show More </h6>
                      <Image
                        src="/home/Vector (9).png"
                        className="mt-2"
                        alt=""
                        height="9"
                        width="9"
                        layout="fixed"
                      />
                    </div>
                  </div> */}

                  {/*========== Requirements ==========*/}

                  {/* <div
                    className="card shadow border-0"
                    style={{ marginTop: "50px", background: "#252525" }}
                  >
                    <h3 className={style.requirements}>Requirements</h3>
                    <ul>
                      <div className={style.requP}>
                        <li>
                          This course is for beginners to graphic design theory
                          and for anyone who wants to learn the basic principles
                          of color theory, typography, layout design,
                          photography, logo design, branding, and more as it
                          relates to graphic design.
                        </li>
                      </div>
                      <div className={style.requP}>
                        <li>
                          You will learn intermediate and advanced terminology
                          that you can use to incorporate in graphic design,
                          user interfaces, mobile app design, logo design,
                          t-shirt design, and other digital or print mediums.
                        </li>
                      </div>
                      <div className={style.requP}>
                        <li>
                          Project files and resources can be found in available
                          lessons located directly in this course.
                        </li>
                      </div>
                    </ul>
                  </div> */}

                  <h2 className={style.content}>Course content</h2>
                  <h4 className={style.contentH4}>
                    13 sections • 83 lectures • 10h 9m total length
                  </h4>
                  <div>
                    {course.module_details.length != 0 ? (
                      course.module_details.map(({ title, details }) => (
                        <Accordion
                          key={course._id}
                          defaultActiveKey="0"
                          className={`card  border-0 rounded-4 ${style.items}`}
                        >
                          <Accordion.Item className={`border-0 `}>
                            <Accordion.Header className={`border-0`}>
                              <div className={`border-0  ${style.faqH5}`}>
                                {title}
                              </div>
                            </Accordion.Header>
                            <Accordion.Body className={style.faqP}>
                              <ul
                                dangerouslySetInnerHTML={{ __html: details }}
                              />
                              {/* {details} */}
                            </Accordion.Body>
                          </Accordion.Item>
                        </Accordion>
                      ))
                    ) : (
                      <Accordion
                        defaultActiveKey="0"
                        className={`card  border-0 rounded-4 ${style.items}`}
                      >
                        <Accordion.Item className={`border-0 `}>
                          <Accordion.Header className={`border-0`}>
                            <div className={`border-0  ${style.faqH5}`}>
                              Module is not published
                            </div>
                          </Accordion.Header>
                          <Accordion.Body className={style.faqP}>
                            {/* <ul dangerouslySetInnerHTML={{ __html: details }} /> */}
                            Module is not published
                          </Accordion.Body>
                        </Accordion.Item>
                      </Accordion>
                    )}
                  </div>
                  <div className="d-grid mb-3" style={{ marginTop: "16px" }}>
                    <a
                      href={course.pdf_file}
                      className={`${styles.btm} text-center text-capitalize text-decoration-none`}
                      type="button"
                      target="_blank"
                    >
                      Show Full Details
                    </a>
                  </div>
                  <div className="col-5"></div>
                </div>

                {/* ======== Right card ======== */} 

                <div id="fixedDivId" style={{ position: isFixed ? 'fixed' : 'static', top: 0}} className="col-12 col-lg-5">
                  <div className={`mt-5 ${style.stickyCard}`}>
                    <div
                      className={`card border-0 shadow mb-3`}
                      style={{ weight: "456px" }}
                    >
                      <div className="m-3">
                        <Image
                          src={course.images}
                          alt=""
                          className="card-img-top"
                          height="236"
                          width="418"
                          layout="fixed"
                        />
                      </div>
                      <div className="" style={{ marginLeft: "23px" }}>
                        <p className={style.cardTime}>{course.starting_date}</p>
                        <h2 className={style.cardPrice}>৳{course.money}</h2>
                      </div>
                      <div className="m-3 d-grid">
                        <Link
                          href={course.Enroll_form}
                          target="_blank"
                          className={`${styles.btm} nav-link text-center text-decoration-none`}
                        >
                          Enrolls Now
                        </Link>
                      </div>
                      <div className="" style={{ marginLeft: "36px" }}>
                        <h6 className={`mt-3 ${style.cardH6}`}>
                          This Courses Includes
                        </h6>
                        <div className="d-flex">
                          <img
                            src="/icon/schedule_FILL0_wght400_GRAD0_opsz48 1.png"
                            height={30}
                            width={30}
                          />
                          <p className={style.cardIP}>
                            10 hours on-demand video
                          </p>
                        </div>
                        <div className="d-flex ">
                          <img
                            src="/icon/Group 3576.png"
                            height={30}
                            width={30}
                          />
                          <p className={style.cardIP}>1 article</p>
                        </div>
                        <div className="d-flex ">
                          <img
                            src="/icon/Group 3575.png"
                            height={30}
                            width={30}
                          />
                          <p className={style.cardIP}>
                            14 downloadable resources
                          </p>
                        </div>
                        <div className="d-flex ">
                          <img
                            src="/icon/Group 3574.png"
                            height={30}
                            width={30}
                          />
                          <p className={style.cardIP}>Full lifetime access</p>
                        </div>
                        <div className="d-flex ">
                          <img
                            src="/icon/Group 3573.png"
                            height={30}
                            width={30}
                          />
                          <p className={style.cardIP}>
                            Certificate of completion
                          </p>
                        </div>
                      </div>

                      <div className="row mt-2" style={{ marginLeft: "30px" }}>
                        <div className="col-6">
                          <div className="d-flex ">
                            <img
                              src="/icon/confirmation_number_FILL0_wght400_GRAD0_opsz48 1.png"
                              height={30}
                              width={30}
                            />
                            <u>
                              <p className={style.cardH5}>Promo Code</p>
                            </u>
                          </div>
                        </div>
                        <div className="col-6 mb-3">
                          <div className="d-flex ">
                            <img
                              src="/icon/Vector (10).png"
                              height={30}
                              width={30}
                            />
                            <u>
                              <p className={style.cardH5}>Share</p>
                            </u>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        );
      })}
    </div>
  );
};

const content = [
  {
    question: "Day 1",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 2",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 3",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 4",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 5",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 6",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
  {
    question: "Day 7",
    answer:
      "What is Graphic Design? Difference between Photoshop and Illustrator",
  },
];

export async function getServerSideProps({ params: { slug } }) {
  let course = await fetch(
    `https://e-learning-server-five.vercel.app/courses/${slug}`
  );
  let myCourse = await course.json();
  return {
    props: { myCourse: myCourse },
  };
}
export default slug;
